# 1. Find all things that have been named after (P138) any president of 
#    Poland (Q1054799). For each such thing return this 
#    thing (e.g., wd:Q315658), its label in Polish 
#    (e.g., Uniwersytet Wrocławski) and the name of the 
#    president (e.g., Bolesław Bierut).

SELECT ?thing ?thingLabel ?president ?presidentLabel
WHERE
{
    ?president wdt:P39 wd:Q1054799 .
    ?thing wdt:P138 ?president .
     
   SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". 
  }
}

# 2. Find all popes with a child that was a pope too.

SELECT ?pope ?popeLabel ?popeChildLabel
WHERE
{
  	?pope wdt:P39 wd:Q19546. 
    ?pope wdt:P40 ?popeChild.
    ?popeChild wdt:P39 wd:Q19546.
  
   SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". 
  }
}

# 3. Find all popes without children, i.e., either their P40 property
#    has value no value (as in the lecture wdno:P40) or they don't 
#    have P40 property at all.

SELECT ?pope ?popeLabel
WHERE
{  
    {
  	  ?pope wdt:P39 wd:Q19546. 
      ?pope p:P40 ?child .
      ?child rdf:type wdno:P40 .
    } UNION {
      ?pope wdt:P39 wd:Q19546. 
      ?pope p:P40 ?child .
      FILTER (!BOUND(?child)).
    }
   
   SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". 
  }
}

# 4. Consider politicians that have a label in Polish language, were 
#    born in Poland but have some other citizenship. For each such citizenship 
#    (other that Polish) return the number of such politicians.

# 5. Find all universities that are at most 200 km from Wrocław and are 
#    not in Poland. Visualize them on a map. (look at the airport example).

SELECT ?place ?placeLabel ?placeCountryLabel ?location
WHERE
{
  wd:Q1799 wdt:P625 ?wrocLoc .
  
  SERVICE wikibase:around {
    ?place wdt:P625 ?location .
    bd:serviceParam wikibase:center ?wrocLoc .
    bd:serviceParam wikibase:radius "200" .
  } .
  
  FILTER EXISTS { ?place wdt:P31/wdt:P279* wd:Q3918 } .
  ?place wdt:P17 ?placeCountry.
  FILTER (?placeCountry != wd:Q36) .
  
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" .
  } 
}